name: nusdi-dev
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
    - tqdm
    - numpy<2
    - matplotlib
    - opencv-python
    - shapely
    - git+https://github.com/lettlini/core-data-utils.git
    - ipykernel
